### ISSUE TITLE
Sections getting hidden when you fill the large description

### ISSUE THREAD

**Issue by hirenchauhan2** [0xShapeShifter/readme-md#2]
Since you have added a fixed height card, you might add the style `overflow-y: auto` or Tailwind class `overflow-y-auto` instead of `overflow-hidden` on the content container to have a scrollbar whenever the content becomes larger than the container height.

![image](https://user-images.githubusercontent.com/8999668/215031907-49f5e083-43b3-41a1-9348-f0e4bb088925.png)

Fixed!
![image](https://user-images.githubusercontent.com/8999668/215033650-6d879492-4b99-4f56-ad8d-a57dcebabf34.png)

**Comment by essensdev** [comment]
Hey there! Thank you for joining the build) Actually, this was my point exactly. I didn't want the container to grow with the size of the content. If I understood you correctly.

**Comment by hirenchauhan2** [comment]
> Hey there! Thank you for joining the build) Actually, this was my point exactly. I didn't want the container to grow with the size of the content. If I understood you correctly.

Yes, that's correct. the container's size won't grow with the size of the content; but, the inner part where the content is shown, will have the scrollbar so that users can see the rest of the content and not cropped one which the current scene.

You can check the PR #3 preview [here](https://readme-md-git-fork-hirenchauhan2-fix-prev-b431b8-0xshapeshifter.vercel.app/create) to verify the workings.
