### ISSUE TITLE
New suggesetion

### ISSUE THREAD

**Issue by priyankarpal** [0xShapeShifter/readme-md#5]
hi, first I wanna say that You made an awesome product. 

On tip that pleases fix navbar design. It's looking odd. You can center all of your nav items or float right. It would be great if you do it. 

![Screenshot from 2023-01-29 19-04-35](https://user-images.githubusercontent.com/88102392/215329801-e80cb5e2-b82f-4a14-8a53-53ce46b478d9.png)

**Comment by essensdev** [comment]
Hi! Thank you for your suggestions and support. Since it's a beta, I will be adding more features in the future. And honestly, the navbar is ugly as it is right now, and I will redo it in a couple of days)
