### ISSUE TITLE
Tab Category Text Disappears When Selecting

### ISSUE THREAD

**Issue by impressivewebs** [0xShapeShifter/readme-md#7]
On the form, when selecting "Basic Info", "Skills", or "Contacts", the text turns white on the white background, so it's no longer visible while you're in that section. See screenshot:

![q2Kb0Ge](https://user-images.githubusercontent.com/558709/228691218-c78979e8-5a07-46a1-b510-b371c47cb39e.png)

Is it supposed to do this?

**Comment by essensdev** [comment]
Thank you! Fixed just now
